name: Release
on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
    strategy:
      matrix:
        os: [{ os: ubuntu-latest, zipfile: linux }, { os: macos-latest, zipfile: mac }]
    runs-on: ${{ matrix.os.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Build
        run: |
          make build
          tar -czvf ltag-${{ github.ref_name }}-${{ matrix.os.zipfile }}.tar.gz ./ltag
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ltag-${{ github.ref_name }}-${{ matrix.os.zipfile }}.tar.gz
          fail_on_unmatched_files: true
